// This file is generated by Slice Machine. Update with care!

import Blockquote from "./Blockquote";
import Content from "./Content";
import Image from "./Image";

export { Blockquote, Content, Image };

export const components = {
  blockquote: Blockquote,
  content: Content,
  image: Image,
};
